apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-microservice
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yuzelt/argocd_yuzelt.git
    targetRevision: main
    path: lab-microservice-chart
    helm:
      # Yol A: values.yaml source of truth.
      # Burada parameters KULLANMIYORUZ.
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
